import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Sale } from '../../types'
import { formatCurrency, formatDateTime } from '../../lib/utils'

interface ShopInfo {
  name: string
  address: string
  phone: string
  gstin?: string
}

export const generateInvoicePDF = (sale: Sale, shopInfo: ShopInfo): jsPDF => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.width

  // Header background
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageWidth, 35, 'F')

  // Shop Name
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(shopInfo.name, 15, 14)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(shopInfo.address, 15, 20)
  doc.text(`Phone: ${shopInfo.phone}`, 15, 25)
  if (shopInfo.gstin) {
    doc.text(`GSTIN: ${shopInfo.gstin}`, 15, 30)
  }

  // TAX INVOICE label
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('TAX INVOICE', pageWidth - 15, 16, { align: 'right' })

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text(`Bill No: ${sale.bill_no}`, pageWidth - 15, 22, { align: 'right' })
  doc.text(`Date: ${formatDateTime(sale.created_at || sale.date)}`, pageWidth - 15, 27, { align: 'right' })

  // Customer info
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(9)
  let y = 42
  if (sale.customer_name) {
    doc.text(`Customer: ${sale.customer_name}`, 15, y)
    if (sale.phone) doc.text(`Phone: ${sale.phone}`, 15, y + 5)
    y += 12
  }

  // GST type
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text(
    `GST Type: ${sale.is_inter_state ? 'IGST (Inter-State)' : 'CGST + SGST (Intra-State)'}`,
    15, y
  )
  doc.text(`Payment: ${(sale.payment_method || 'cash').toUpperCase()}`, pageWidth - 15, y, { align: 'right' })
  y += 6

  // Items table
  const tableRows = (sale.items || []).map((item, i) => {
    const amount = item.qty * item.sell_price - item.discount
    const gst = (amount * item.gst_rate) / 100
    return [
      i + 1,
      item.product_name,
      item.qty,
      formatCurrency(item.sell_price),
      item.gst_rate + '%',
      item.discount > 0 ? formatCurrency(item.discount) : '-',
      formatCurrency(amount),
    ]
  })

  autoTable(doc, {
    startY: y + 2,
    head: [['#', 'Item', 'Qty', 'Rate', 'GST%', 'Disc', 'Amount']],
    body: tableRows,
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: [30, 30, 30],
    },
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [248, 248, 255] },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      2: { halign: 'center' },
      3: { halign: 'right' },
      4: { halign: 'center' },
      5: { halign: 'right' },
      6: { halign: 'right' },
    },
  })

  // Summary
  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6
  const rightX = pageWidth - 15
  const leftX = pageWidth - 65

  doc.setFontSize(9)
  doc.setTextColor(80, 80, 80)
  doc.text('Subtotal:', leftX, finalY)
  doc.text(formatCurrency(sale.subtotal), rightX, finalY, { align: 'right' })

  if (sale.discount > 0) {
    doc.text('Discount:', leftX, finalY + 5)
    doc.setTextColor(220, 50, 50)
    doc.text(`-${formatCurrency(sale.discount)}`, rightX, finalY + 5, { align: 'right' })
    doc.setTextColor(80, 80, 80)
  }

  // GST breakup
  if (!sale.is_inter_state) {
    doc.text(`CGST (${sale.items?.[0]?.gst_rate / 2 || 9}%):`, leftX, finalY + 10)
    doc.text(formatCurrency(sale.gst_amount / 2), rightX, finalY + 10, { align: 'right' })
    doc.text(`SGST (${sale.items?.[0]?.gst_rate / 2 || 9}%):`, leftX, finalY + 15)
    doc.text(formatCurrency(sale.gst_amount / 2), rightX, finalY + 15, { align: 'right' })
  } else {
    doc.text(`IGST (${sale.items?.[0]?.gst_rate || 18}%):`, leftX, finalY + 10)
    doc.text(formatCurrency(sale.gst_amount), rightX, finalY + 10, { align: 'right' })
  }

  // Total
  const totalY = !sale.is_inter_state ? finalY + 22 : finalY + 17
  doc.setFillColor(99, 102, 241)
  doc.rect(leftX - 5, totalY - 5, rightX - leftX + 20, 12, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('TOTAL:', leftX, totalY + 2)
  doc.text(formatCurrency(sale.total), rightX, totalY + 2, { align: 'right' })

  // Footer
  doc.setTextColor(150, 150, 150)
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  const pageHeight = doc.internal.pageSize.height
  doc.text('Thank you for your purchase! • Generated by Advanced Invento', pageWidth / 2, pageHeight - 8, { align: 'center' })

  return doc
}
